"""Add leaderboard relationship to User model

Revision ID: feb1122a2a9c
Revises: db3e5e262f3a
Create Date: 2023-09-10 14:06:46.362820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb1122a2a9c'
down_revision: Union[str, None] = 'db3e5e262f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'new_column_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('new_column_name', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
